apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  namespace: grafana  
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/grafana  # Replace with the path to your host directory

