apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-pod-binding
  namespace: example-namespace
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: system:serviceaccounts:example-namespace
roleRef:
  kind: Role
  name: nginx-role
  apiGroup: rbac.authorization.k8s.io

