apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  namespace: example-namespace
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi

