version: '3'

services:
  web:
    build: .
    ports:
      - "8081:80"
    depends_on:
      - db
    volumes:
      - ./html:/var/www/html
      - ./html/inc:/var/www/html/inc  # Mount dbinfo.inc file

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rdspass123
      MYSQL_DATABASE: cloudPlusPlusLab
      MYSQL_USER: rdsuser123
      MYSQL_PASSWORD: rdspass123
    ports:
      - "3306:3306"

